server:
  port: 9003
  
eureka:  instance:    hostname: localhost
    
    
spring:  application:    name: api-gateway
  cloud:    gateway:      routes:      - id: COMPANY-SERVICE
        uri: lb://COMPANY-SERVICE
        predicates:        - Path=/company/**
      - id: TEAM-SERVICE
        uri: lb://TEAM-SERVICE
        predicates:        - Path=/team/**  main:    allow-bean-definition-overriding: true               